------------------create table customer-----------------------------
create table customer(
      log_id bigint generated by default as identity primary key,
      customer_id SERIAL UNIQUE, --in practice, customer_id should not be unique in this table because customers are allowed to change their birth info
      birth_location int, --customers' input info, startdard format is six digit postcode (China)
      birth_datetime timestamp without time zone  ----customers' input info, stardard format is yyyy-mm-dd	 
  );
-- DROP TABLE if exists customer cascade;


----------------create table logic1---------------------------------
create table logic1(
      log_id bigint generated by default as identity primary key,
      customer_id int,                                              --duplicate from the customer table
      birth_location int,                                           --duplicate from the customer table
      birth_datetime timestamp without time zone,                   --duplicate from the customer table
      birth_gmt0 timestamp without time zone,                       --calculate in logic1
      birth_spn timestamp without time zone,                        --calculate in logic1, spn = birth_since_pre_noon 
      birth_lng float,                                              --calculate in logic1
      birth_lat float,                                              --calculate in logic1
      four_mins_every_degree float                                  --calculate in logic1
);
-- DROP TABLE if exists logic1 cascade;


------------------------create table logic2------------------------------------
create table logic2(
      log_id bigint generated by default as identity primary key,
      customer_id int,                                                    --duplicate from the logic1 table
      birth_location int,                                                 --duplicate from the logic1 table
      birth_datetime timestamp without time zone,                         --duplicate from the logic1 table
      birth_gmt0 timestamp without time zone,                             --duplicate from the logic1 table
      birth_spn timestamp without time zone,                              --duplicate from the logic1 table
      birth_lng float,                                                    --duplicate from the logic1 table
      birth_lat float,                                                    --duplicate from the logic1 table
      four_mins_every_degree float,                                       --duplicate from the logic1 table
      spn_hours float,                                                    --calculate in logic2
      spn_mins float,                                                     --calculate in logic2
      add_ten_seconds float,                                              --calculate in logic2
      comp_mins_spn float,                                                --calculate in logic2
      st_for_pre_noon float                                               --calculate in logic2
);
-- DROP TABLE if exists logic2 cascade;


------------------------create table logic3------------------------------------
create table logic3(
     log_id bigint generated by default as identity primary key,
      customer_id int,                                          --duplicate from the logic2 table
      birth_location int,                                       --duplicate from the logic2 table
      birth_datetime timestamp without time zone,               --duplicate from the logic2 table
      birth_gmt0 timestamp without time zone,                   --duplicate from the logic2 table
      birth_spn timestamp without time zone,                    --duplicate from the logic2 table
      birth_lng float,                                          --duplicate from the logic2 table
      birth_lat float,                                          --duplicate from the logic2 table
      four_mins_every_degree float,                             --duplicate from the logic2 table
      spn_hours float,                                          --duplicate from the logic2 table
      spn_mins float,                                           --duplicate from the logic2 table
      add_ten_seconds float,                                    --duplicate from the logic2 table
      comp_mins_spn float,                                      --duplicate from the logic2 table
      st_for_pre_noon float,                                    --duplicate from the logic2 table
      birth_st float,                                           --calculate in logic3
      stA float,                                                --calculate in logic3
      stB float,                                                --calculate in logic3
      laA float,                                                --calculate in logic3
      laB float                                                 --calculate in logic3
);
-- DROP TABLE if exists logic3 cascade;


------------------------create table logic4------------------------------------
create table logic4(
  log_id bigint generated by default as identity primary key,
  customer_id int,                                              --duplicate from the logic3 table
  birth_st float,                                               --duplicate from the logic3 table
  birth_lat float,                                              --duplicate from the logic3 table
  laA float,                                                    --duplicate from the logic3 table
  laB float,                                                    --duplicate from the logic3 table
  stA float,                                                    --duplicate from the logic3 table
  stB float,                                                    --duplicate from the logic3 table
  h1_laAstA float,                                              --calculate in logic4
  h1_laAstB float,                                              --calculate in logic4
  h1_laBstA float,                                              --calculate in logic4
  h1_laBstB float,                                              --calculate in logic4
  h2_laAstA float,                                              --calculate in logic4
  h2_laAstB float,                                              --calculate in logic4
  h2_laBstA float,                                              --calculate in logic4
  h2_laBstB float,                                              --calculate in logic4
  h3_laAstA float,                                              --calculate in logic4
  h3_laAstB float,                                              --calculate in logic4
  h3_laBstA float,                                              --calculate in logic4
  h3_laBstB float,                                              --calculate in logic4
  h10_laAstA float,                                             --calculate in logic4
  h10_laAstB float,                                             --calculate in logic4
  h10_laBstA float,                                             --calculate in logic4
  h10_laBstB float,                                             --calculate in logic4
  h11_laAstA float,                                             --calculate in logic4
  h11_laAstB float,                                             --calculate in logic4
  h11_laBstA float,                                             --calculate in logic4
  h11_laBstB float,                                             --calculate in logic4
  h12_laAstA float,                                             --calculate in logic4
  h12_laAstB float,                                             --calculate in logic4
  h12_laBstA float,                                             --calculate in logic4
  h12_laBstB float                                              --calculate in logic4
);
-- DROP TABLE if exists logic4 cascade;


------------------------create table natal_part1------------------------------------
create table natal_part1(
      log_id bigint generated by default as identity primary key,
      customer_id int,    --duplicate from the logic4 table
      h1_dec float,       --calculate in natal_part1
      h1_deg1 float,      --calculate in natal_part1
      h1_deg2 float,      --calculate in natal_part1
      h2_dec float,       --calculate in natal_part1
      h2_deg1 float,      --calculate in natal_part1
      h2_deg2 float,      --calculate in natal_part1
      h3_dec float,       --calculate in natal_part1
      h3_deg1 float,      --calculate in natal_part1
      h3_deg2 float,      --calculate in natal_part1
      h10_dec float,      --calculate in natal_part1
      h10_deg1 float,     --calculate in natal_part1
      h10_deg2 float,     --calculate in natal_part1
      h11_dec float,      --calculate in natal_part1
      h11_deg1 float,     --calculate in natal_part1
      h11_deg2 float,     --calculate in natal_part1
      h12_dec float,      --calculate in natal_part1
      h12_deg1 float,     --calculate in natal_part1
      h12_deg2 float      --calculate in natal_part1
);
-- DROP TABLE if exists natal_part1 cascade;


------------------------create table natal_part2------------------------------------
create table natal_part2(
      log_id bigint generated by default as identity primary key,
      customer_id int,          --duplicate from the natal_part1 table
      h4_dec float,             --calculate in natal_part2
      h4_deg1 float,            --calculate in natal_part2
      h4_deg2 float,            --calculate in natal_part2
      h5_dec float,             --calculate in natal_part2
      h5_deg1 float,            --calculate in natal_part2
      h5_deg2 float,            --calculate in natal_part2
      h6_dec float,             --calculate in natal_part2
      h6_deg1 float,            --calculate in natal_part2
      h6_deg2 float,            --calculate in natal_part2
      h7_dec float,             --calculate in natal_part2
      h7_deg1 float,            --calculate in natal_part2
      h7_deg2 float,            --calculate in natal_part2
      h8_dec float,             --calculate in natal_part2
      h8_deg1 float,            --calculate in natal_part2
      h8_deg2 float,            --calculate in natal_part2
      h9_dec float,             --calculate in natal_part2
      h9_deg1 float,            --calculate in natal_part2
      h9_deg2 float             --calculate in natal_part2
);
-- DROP TABLE if exists natal_part2 cascade;





